### ISSUE TITLE
跳不出循环

### ISSUE THREAD

**Issue by here-Leslie-Lau** [zhengsh/ssm-laboratory#1]
在order-service/src/main/java/cn/edu/cqvie/order/lb/MyLB.java下，有个方法里面有do-while循环，其中while括号内要加上"非运算符",不然方法成功之后无法跳出循环。

**Comment by zhengsh** [comment]
不会，这里是do-while代码块会先执行，do 里面的内容，如果第一次执行失败，那么会重新执行从 atomicInteger 对象中去获取自增值。然后通过 CAS 无锁的方式去修改自增值，从而保证自增操作的原子性和效率
